-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'background {' on line 1
-- all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations

-- TODO: manual review — unknown section 'input-field {' on line 16

-- TODO: manual review — unknown section 'label {' on line 41
-- TODO: center text
