-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local terminal = "kitty"
local closeMenu = "vicinae vicinae://close"
local menu = "vicinae toggle"
local fileManager = "nemo"
local scriptsDir = "~/.config/hypr/scripts/"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.exec_cmd("~/.config/tmux/on-open-tmux.sh"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- bind = $mainMod, M, exit,
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
-- bind = $mainMod, R, exec, $menu
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
-- bind = $mainMod SHIFT, F, fullscreen, 0
hl.bind(mainMod .. " + ALT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + N", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(scriptsDir .. "/GameMode.sh"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd(closeMenu .. " || vicinae vicinae://launch/core/search-emojis"))
hl.bind(mainMod .. " + CTRL + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("kalk"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("zen-browser --ProfileManager"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("blueman-manager"))
-- bind = $mainMod SHIFT, H, exec, hyprpanel -t settings-dialog

hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(scriptsDir .. "/ChangeLayout.sh"))

-- Master Layout
hl.bind(mainMod .. " + CTRL + D", hl.dsp.layout("removemaster"))
hl.bind(mainMod .. " + I", hl.dsp.layout("addmaster"))
-- bind = $mainMod, period, layoutmsg, cyclenext
-- bind = $mainMod, comma, layoutmsg, cycleprev
-- bind = $mainMod, M, exec, hyprctl dispatch splitratio 0.3
-- bind = $mainMod, P, pseudo, # dwindle
hl.bind(mainMod .. " + CTRL + Return", hl.dsp.layout("swapwithmaster"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("hyprctl dispatch splitratio -0.3"))

hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("killall wlogout || wlogout --protocol layer-shell"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("killall wlogout || wlogout --protocol layer-shell"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("killall slurp || grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd(scriptsDir .. "/screenshot.sh"))
-- hyprshot commands
-- Screenshot a window
-- bind = $mainMod, PRINT, exec, hyprshot -m window
-- Screenshot a monitor
-- bind = , PRINT, exec, hyprshot -m output
-- Screenshot a region
hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m region"))
-- XF86TouchpadToggle doesn't work
hl.bind("XF86TouchpadOn", hl.dsp.exec_cmd("notify-send -h string:x-canonical-private-synchronous:tOucHpAd \"Enable Touchpad\" -t 2000"))
hl.bind("XF86TouchpadOff", hl.dsp.exec_cmd("notify-send -h string:x-canonical-private-synchronous:tOucHpAd \"Disable Touchpad\" -t 2000"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- swapwindow
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.swap({ direction = "d" }))
hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.swap({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Alt switch to workspace
hl.bind(mainMod .. " + SHIFT + semicolon", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + u", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + i", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + o", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + p", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + ALT + semicolon", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + ALT + l", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + ALT + k", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + ALT + j", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + ALT + u", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + ALT + i", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + ALT + o", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + ALT + p", hl.dsp.window.move({ workspace = 8 }))

-- # Switch to a submap called `resize`.
-- bind = $mainMod, m, submap, monitor_related
--
-- # Start a submap called "resize".
-- submap = monitor_related
--
-- # Set repeatable binds for resizing the active window.
-- binde = , h, focusmonitor, l
-- binde = , l, focusmonitor, r
-- binde = , j, focusmonitor, d
-- binde = , k, focusmonitor, u
--
-- # Use `reset` to go back to the global submap
-- bind = CTRL, bracketleft, submap, reset
-- submap = reset
--
-- monitor related keybinds
hl.bind(mainMod .. " + ALT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + ALT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + ALT + h", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mainMod .. " + CTRL + ALT + l", hl.dsp.window.move({ monitor = "r" }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + CTRL + S", hl.dsp.window.move({ workspace = "special:magic" }))
-- TODO: implement stuffs for scratch scratchpad
hl.bind(mainMod .. " + D", hl.dsp.workspace.toggle_special("scratch"))
hl.bind(mainMod .. " + CTRL + D", hl.dsp.window.move({ workspace = "special:scratch" }))
hl.bind(mainMod .. " + ALT + D", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspace $(hyprctl activeworkspace | awk '(NR==1){print $3}')"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + semicolon", hl.dsp.focus({ workspace = "previous" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Resize windows using keyboard
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- wofi cliphist
hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd(closeMenu .. " || vicinae vicinae://launch/clipboard/history"))

-- Volume and Media Control
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5 && notify-send -e -h string:x-canonical-private-synchronous:mY_N0tiF -a \"changeVolume\" -u low -i audio-volume-high -h int:value:\"$(pamixer --get-volume)\" \"Volume: $(pamixer --get-volume)%\""), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5 && notify-send -e -h string:x-canonical-private-synchronous:mY_N0tiF -a \"changeVolume\" -u low -i audio-volume-high -h int:value:\"$(pamixer --get-volume)\" \"Volume: $(pamixer --get-volume)%\""), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t && dunstify -h string:x-canonical-private-synchronous:m1c \"Mic is $([[ $(pamixer --default-source --get-mute) == 'true' ]] && echo 'off' || echo 'on')\""))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- brightness
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(scriptsDir .. "/brightness-control.sh --dec"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(scriptsDir .. "/brightness-control.sh --inc"))

-- bind = $mainMod, asciitilde, exec, kill -s 9 $(pidof nwg-drawer)
hl.bind(mainMod .. " + CTRL + bracketleft", hl.dsp.exec_cmd("dunstctl close-all"))
