-- important stuffs
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
-- exec-once = wl-paste --watch cliphist store

-- personal modifications
-- exec-once=webcord
-- exec-once=librewolf & disown
-- exec-once=batsignal -b -p -w 20

hl.env("MOZ_ENABLE_WAYLAND", "1")
-- env = QT_QPA_PLATFORM,wayland
-- env = QT_QPA_PLATFORMTHEME,qt6ct
hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("KDE_SESSION_VERSION", "5")
-- env = QT_AUTO_SCREEN_SCALE_FACTOR,1
-- env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
hl.env("GDK_BACKEND", "wayland")
-- env = GTK_THEME,Adwaita:dark
-- env = GTK2_RC_FILES,/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
-- env = QT_STYLE_OVERRIDE,Breeze-Dark
-- env = GTK_THEME,Breeze-Dark

-- cliphist
-- exec-once = wl-paste --type text --watch cliphist store #Stores only text data
-- exec-once = wl-paste --type image --watch cliphist store #Stores only image data

-- wofi

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("GDK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("QT_SCALE_FACTOR", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "0")

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("wal -R")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("poweralertd")
    hl.exec_cmd("dunst")
    hl.exec_cmd("nm-applet --indicator & disown")
    hl.exec_cmd("kwalletd6")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("discord")
    hl.exec_cmd("spotify")
    hl.exec_cmd("steam")
    hl.exec_cmd("cbatticon")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("zen-browser -P \"Default (release)\"", { workspace = "3 silent" })
    hl.exec_cmd("zen-browser -P work", { workspace = "1 silent" })
    hl.exec_cmd("zen-browser -P others", { workspace = "1 silent" })
    hl.exec_cmd("swaybg -m fill -i ~/Pictures/wallpapers/Wallpaper-Bank/wallpapers/Night_City.png")
    hl.exec_cmd("~/.config/tmux/auto-attach.sh", { workspace = "magic" })
end)

