-- windowrule v2
-- windowrulev2 = workspace 1, class:^(thunderbird)$
-- windowrulev2 = workspace 2, class:^(firefox)$
-- windowrulev2 = workspace 2, class:^(Firefox-esr)$
-- windowrulev2 = workspace 2, class:^(Microsoft-edge-beta)$ 
-- windowrulev2 = workspace 3, class:^([Tt]hunar)$
-- windowrulev2 = workspace 4 silent, class:^(spotify)$
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "spotify-workspace",
    match = {
        initial_title = "^(Spotify)(.*)$",
    },
    workspace = "4 silent",
})

-- windowrulev2 = workspace 5 silent, class:^([Ss]team)$,title:^([Ss]team)$
-- windowrulev2 = workspace 5 silent, class:^(lutris)$
hl.window_rule({
    name = "discord-workspace",
    match = {
        initial_class = "^(discord)$",
    },
    workspace = "5 silent",
})

hl.window_rule({
    name = "vesktop-workspace",
    match = {
        initial_class = "^(vesktop)$",
    },
    workspace = "5 silent",
})

hl.window_rule({
    name = "webcord-workspace",
    match = {
        initial_class = "^(WebCord)$",
    },
    workspace = "5 silent",
})

-- windowrulev2 = workspace 6, class:^(virt-manager)$
hl.window_rule({
    name = "steam-workspace",
    match = {
        initial_class = "^(steam)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    name = "audacious-workspace",
    match = {
        initial_class = "^([Aa]udacious)$",
    },
    workspace = "9 silent",
})

hl.window_rule({
    name = "emulator-float",
    match = {
        class = "^Emulator$",
    },
    float = true,
})

hl.window_rule({
    name = "emulator-size",
    match = {
        class = "^Emulator$",
        initial_title = "^Android Emulator.*$",
    },
    size = "475 987",
})

-- design
hl.workspace_rule({
    workspace = "special:magic",
    gaps_in = 5,
    gaps_out = 20,
    on_created_empty = "~/.config/tmux/on-open-tmux.sh",
})

hl.window_rule({
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    opacity = "0.0 override",
    no_anim = true,
    no_initial_focus = true,
    max_size = { 1, 1 },
    no_blur = true,
})

-- disable fade animation for vicinae only
hl.layer_rule({
    match = { namespace = "vicinae" },
    no_anim = true,
    blur = true,
    ignore_alpha = 0,
})
