#!/bin/bash
# copy-pasted from sh generated by JaKooLit

# dunst_notif="$HOME/.config/dunst/images/bell.png"

LAYOUT=$(hyprctl -j getoption general:layout | jq '.str' | sed 's/"//g')

	# hyprctl keyword unbind SUPER,K

case $LAYOUT in
"dwindle")
	hyprctl keyword general:layout master
	# hyprctl keyword unbind SUPER,J
	# hyprctl keyword bind SUPER,J,cyclenext
	# hyprctl keyword bind SUPER,K,cyclenext,prev
	# hyprctl keyword bind SUPER,O,togglesplit
	notify-send -h string:x-canonical-private-synchronous:lAyoUt -u low "Master Layout"
	;;
"master")
	hyprctl keyword general:layout dwindle
	# hyprctl keyword unbind SUPER,J
	# hyprctl keyword unbind SUPER,K
	# hyprctl keyword unbind SUPER,O
	# hyprctl keyword bind SUPER,N,togglesplit
	notify-send -h string:x-canonical-private-synchronous:lAyoUt -u low "Dwindle Layout"
	;;
*) ;;

	# hyprctl keyword bind SUPER,K,layoutmsg,cycleprev

esac
